export enum FlowTabName {
  InitialCustomer = 'initialCustomerTab',
  Customer = 'customerTab',
  Loan = 'loanTab',
  SlikOrder = 'slikOrderTab',
  Slik = 'slikTab',
  SlikResult = 'slikResultTab',
  Collateral = 'collateralTab',
  guarantor = 'guarantorTab',
  FinancialStatement = 'financialStatementTab',
  CreditAnalysis = 'creditAnalysisTab',
  CreditAnalysisLog = 'creditAnalysisLogTab',
  Appraisal = 'appraisalTab',
  Corporate = 'corporateTab',
  Scoring = 'scoringTab',
  CustomerCode = 'customerCodeInfo',
  LoanCode = 'loanCodeInfo',
  Handoff = 'handoffTab',
  Drawdown = 'drawdownTab',
  AccountStatement = 'accountStatementTab',
  NegativeCheck = 'negativeCheckTab',
  GeneralNote = 'generalNoteTab',
  ComplianceApproval = 'complianceApprovalTab',
  LoanApproval = 'loanApprovalTab',
  SurveyOrder = 'surveyOrderTab',
  ScoringField = 'scoringFieldTab',
  ScoringHistory = 'scoringHistoryTab',
}

export type TFlowTabName = `${FlowTabName}`
