sonar.projectKey=LOS-Web-Admin-V3
sonar.projectName=LOS Regular Version 3 (Frontend)
sonar.projectVersion=3.0.0

# Path ke source code
sonar.sources=src

# Untuk TypeScript
sonar.language=ts
sonar.inclusions=src/**/*.ts,src/**/*.vue
sonar.exclusions=**/*.spec.ts,**/*.test.ts

# Path to tsconfig if use TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# URL SonarQube
sonar.host.url=http://172.22.251.7:9000

# Token Authentication
sonar.token=sqp_1fa78e79121397c0abc59993da36ef6739a02f84
